//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public string BookCode { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public string Type { get; set; }
        public decimal Price { get; set; }
    }
}
